[advisories]
ignore = [
    # criterion.rs is a benchmark-only dependency.
    # https://github.com/bheisler/criterion.rs/issues/629
    # Dependency tree:
    # atty 0.2.14
    # └── criterion 0.4.0
    #     └── ring 0.17.0-not-released-yet
    "RUSTSEC-2021-0145",
]

[output]
deny = ["warnings", "yanked", "unsound", "unmaintained"]
quiet = false
